### PR TITLE
adding git + npm + project level support

### PR DESCRIPTION
**Pull request by napisani**
Hi There, 
I know its been a while, but I took a swing at implementing my suggestion here:
https://github.com/smartpde/neoscopes/issues

I don't believe this change set introduces any breaking changes for folks using the current version.

Let me know what you think!

### CODE REVIEW

**Comment by defr0std** [comment]
Thank you for the contribution! Let me first commit the lua formatting options so that we don't have the unnecessary changes due to the formatting. I will then merge it back into your repo :)

**Comment by defr0std** [comment]
Hi @napisani,

Sent our PR request https://github.com/napisani/neoscopes/pull/1 to reformat the code. Could you please merge than one first?

**Comment by napisani** [comment]
awesome! 
sorry for mismatched formatting, merged your suggestions - thank you for that

**Comment by defr0std** [comment]
Thanks!

**Pull request merged**
